on:
  workflow_dispatch: {}
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          architecture: x64
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tar zstd
      - name: Build & Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon -Pkr328appUsername=${{ secrets.PUBLISH_USERNAME }} -Pkr328appPassword=${{ secrets.PUBLISH_PASSWORD }} publishAllToKr328app
        env:
          TAG: ${{ github.event.release.tag_name }}
